#include "Include.h"
DIDOStruct DIDOBuff;
void DIDOInit(void)
{
	asm
	{
		BSET DDRK,#$0B
		BCLR PORTK,#$0B
		
		BSET DDRP,#$FF
		BCLR PTP,#$FF

		BCLR DDRA,#$38
		BCLR PORTA,#$38

		BSET DDRT,#$1D
		BCLR PTT,#$1D

		BSET DDRE,#$40
		BCLR PORTE,#$40

		BCLR DDRH,#$02
		BCLR PTH,#$02

		BCLR DDRB,#$0E
		BCLR PORTB,#$0E
	}
}
void DIDOBuffInit(void)
{
	asm
	{
		BCLR DIDOBuff.data[0],#$FF
		BCLR DIDOBuff.data[1],#$FF
	}
}
void DIDOOutput(void)
{
	asm
	{
	SET0:
		BRSET DIDOBuff.data[0],#$01,FANSET
		BCLR  PORTK,#$01
		BRA  SET1
	FANSET:
		BSET PORTK,#$01
	SET1:
		BRSET DIDOBuff.data[0],#$02,AUXILIARYPOWERSET
		BCLR PORTK,#$02
		BRA SET2
	AUXILIARYPOWERSET:
		BSET PORTK,#$02
	SET2:
		BRSET DIDOBuff.data[0],#$04,MAINNEGATIVERELAYSET
		BCLR PORTK,#$08
		BRA SET3
	MAINNEGATIVERELAYSET :
		BSET PORTK,#$08
	SET3:
		BRSET DIDOBuff.data[0],#$08, MAINPOSITIVERELAYSET
		BCLR PTP, #$01
		BRA SET4
	MAINPOSITIVERELAYSET:
		BSET PTP,#$01
	SET4:
		BRSET DIDOBuff.data[0], #$10, DISCHARGERELAY
		BCLR PTP, #$02
		BRA SET5
	DISCHARGERELAY :
		BSET PTP, #$02
	SET5 :
		BRSET DIDOBuff.data[0], #$20, BEEP
		BCLR PTP, #$80
		BRA SET9
	BEEP :
		BSET PTP, #$80
	SET9 :
		BRSET DIDOBuff.data[1], #$02, GUNSELECTION
		BCLR PTT, #$01
		BRA SET10
	GUNSELECTION :
		BSET PTT, #$01
	SET10:
		BRSET DIDOBuff.data[1],#$04,YELLOWLED
		BCLR PTT,#$04
		BRA SET11
	YELLOWLED:
		BSET PTT,#$04
	SET11:
		BRSET DIDOBuff.data[1],#$08,REDLED
		BCLR PTT,#$08
		BRA SET12
	REDLED:
		BSET PTT,#$08
	SET12:
		BRSET DIDOBuff.data[1],#$10,GREENLED
		BCLR PTT,#$10
		BRA SET13
	GREENLED :
		BSET PTT,#$10
	SET13:
	}
	OSCRITICALENTRY();
}
void DIDOGetInf(void)
{
	asm
	{
	SET0:
		BRSET PORTA,#$08,MAINNEGATIVEFEEDBACK
		BCLR  DIDOBuff.data[0],#$40
		BRA SET1
	MAINNEGATIVEFEEDBACK:
		BSET DIDOBuff.data[0],#$40
	SET1:
		BRSET PORTA,#$10,MAINPOSITIVEFEEDBACK
		BCLR DIDOBuff.data[0],#$80
		BRA SET2
	MAINPOSITIVEFEEDBACK:
		BSET DIDOBuff.data[0],#$80
	SET2:
		BRSET PORTA,#$20,EMERGENCYSTOP
		BSET DIDOBuff.data[1], #$01
		BRA SET3
	EMERGENCYSTOP:
		BCLR DIDOBuff.data[1], #$01
	SET3:
	}
	OSCRITICALENTRY();
}
